apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-kubernetes-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: learn-kubernetes
  template:
    metadata:
      labels:
        app: learn-kubernetes
    spec:
      containers:
      - name: learn-kubernetes
        image: 56faisal/learn-kubernetes:2.0
        ports:
        - containerPort: 3000