apiVersion: v1
kind: Service
metadata:
  name: learn-kubernetes-service
spec:
  selector:
    app: learn-kubernetes
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
